version: 2.1
orbs:
  node: circleci/node@5.1.0
jobs:
  build_and_test:
    executor: node/default
    environment:
      NODE_OPTIONS: --max_old_space_size=4096
    steps:
      - checkout
      - node/install:
          install-yarn: true
          node-version: '18'
      - run:
          command: yarn install
          name: Install packages
      - run:
          command: yarn nw-cdn download
          name: Download nw-data
      - run:
          command: yarn storybook:build
          name: Build Storybook
      # - persist_to_workspace:
      #     root: ~/project
      #     paths: .

workflows:
  test_my_app:
    jobs:
      - build_and_test
